services:
  - postgresql
addons:
  postgresql: "9.6"
language: node_js
node_js:
  - "8"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - export DATABASE_URL='postgres://postgres@localhost:5432/travis_ci_test'
after_success:
- ./bin/codecov